VJMP-JP, AGOV-EN, PHNI-JP cards added
Fluorohydride/ygopro-pre-script pull request #1192
Opened 2023-10-09 00:41 UTC by pokeboyexn

2023-10-09 01:08 UTC, Lyris12 requested changes

2023-10-09 01:08 UTC, Lyris12 commented on scripts/VJMP-JP/c100200244.lua
Already done: #1191

2023-10-09 01:31 UTC, pokeboyexn commented on scripts/VJMP-JP/c100200244.lua
Deleted

2023-10-29 14:09 UTC, Lyris12 requested changes
AGOV-EN cards 091 and 092 have their scripts swapped

2023-10-29 17:01 UTC, pokeboyexn commented
@Lyris12 Thanks for checking. Corrected.

2023-11-08 12:21 UTC, a597449807 reviewed
修复了根据裁定哥布林降下部队无效对方怪兽后，若这张卡变成攻击表示则会和对象怪兽不再建立效果关系，重新变成守备表示后也不会再无效对方怪兽

2023-11-08 12:21 UTC, a597449807 commented on scripts/PHNI-JP/c101203029.lua
> +end
```suggestion
	--cancel target
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e2:SetCode(EVENT_CHANGE_POS)
	e2:SetCondition(s.recon)
	e2:SetOperation(s.reop)
	c:RegisterEffect(e2)	
end
```

2023-11-08 12:21 UTC, a597449807 commented on scripts/PHNI-JP/c101203029.lua
> +	if not c:IsRelateToEffect(e) or c:IsDefensePos() then return end
```suggestion
	if not c:IsRelateToEffect(e) or c:IsDefensePos() or not c:IsCanChangePosition() then return end
```

2023-11-08 12:21 UTC, a597449807 commented on scripts/PHNI-JP/c101203029.lua
> +	return e:GetOwner():IsHasCardTarget(e:GetHandler())
```suggestion
	return e:GetOwner():IsHasCardTarget(e:GetHandler()) and e:GetOwner():IsDefensePos()
```

2023-11-08 12:21 UTC, a597449807 commented on scripts/PHNI-JP/c101203029.lua
> +
```suggestion
	--cancel target
function s.recon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return c:IsPreviousPosition(POS_DEFENSE) and c:IsFaceup() and c:IsAttackPos()
end
function s.reop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=c:GetFirstCardTarget()
	Card.CancelCardTarget(c,tc)
end
```

2023-11-08 12:21 UTC, a597449807 commented on scripts/PHNI-JP/c101203029.lua
> +	e1:SetLabelObject(e0)
```suggestion
```

2024-01-20 03:47 UTC, merged