リペア・ジェネクス・コントローラー new version
Fluorohydride/ygopro-pre-script pull request #1202
Opened 2023-10-13 09:31 UTC by kiritosoft

2023-10-17 08:11 UTC, Lyris12 requested changes
Bug: Restriction from (2) effect does not allow `R-Genex Undine` to be used as Tuner material

2023-10-17 08:11 UTC, Lyris12 commented on scripts/PHNI-JP/c100211051.lua
> +		and g:IsExists(s.smcfilter,1,nil)
```suggestion
		and g:IsExists(s.smcfilter,1,nil,syncard)
```

2023-11-12 11:51 UTC, kiritosoft commented
已知bug：EFFECT_SYNCHRO_MATERIAL_CUSTOM实现的②的效果自肃
对使用aux.AddSynchroMixProcedure作为同调手续的同调怪兽无效（即可以不用次世代调整来同调召唤）

2023-12-11 01:58 UTC, Wind2009-Louse requested changes

2023-12-11 01:58 UTC, Wind2009-Louse commented on scripts/PHNI-JP/c100211051.lua
> +		and （not c:IsStatus(STATUS_TO_HAND_WITHOUT_CONFIRM) or (c:IsStatus(STATUS_TO_HAND_WITHOUT_CONFIRM) and c:IsPublic())
```suggestion
		and (not c:IsStatus(STATUS_TO_HAND_WITHOUT_CONFIRM) or (c:IsStatus(STATUS_TO_HAND_WITHOUT_CONFIRM) and c:IsPublic())
```

2023-12-13 12:11 UTC, kiritosoft commented on scripts/PHNI-JP/c100211051.lua
> +	e2:SetCategory(CATEGORY_SPECIAL_SUMMON)
```suggestion
	e2:SetCategory(CATEGORY_SUMMON)
```

2023-12-18 12:35 UTC, kiritosoft commented
> Bug: Restriction from (2) effect does not allow `R-Genex Undine` to be used as Tuner material

Q.
自分の「リペア・ジェネクス・コントローラー」の『②』の『このターン、自分は「ジェネクス」チューナーをS素材としたS召喚でしかEXデッキからモンスターを特殊召喚できない』効果が適用されているターンです。
戦士族を宣言した「DNA改造手術」の適用中、自分フィールドの「ジェネクス・ニュートロン」を対象として墓地の「焔聖騎士－テュルパン」の『②』の効果を発動し、「焔聖騎士－テュルパン」を装備カード扱いとして「ジェネクス・ニュートロン」に装備されました。
その後、自分は装備カード扱いの「焔聖騎士－テュルパン」の『③：装備モンスターをS素材とする場合、チューナーとして扱う事ができる』効果を適用して、「ジェネクス・ニュートロン」と「ジェネクス・ブラスト」を素材として「混沌魔龍 カオス・ルーラー」のシンクロ召喚を行う事ができますか？
A.
ご質問の場合、挙げていただいた方法で「混沌魔龍 カオス・ルーラー」をシンクロ召喚することはできません。

so，we must check type is TYPE_TUNER

2023-12-18 12:35 UTC, kiritosoft commented on scripts/PHNI-JP/c100211051.lua
> +	return c:IsSetCard(0x2) and c:IsTuner(sc)
```suggestion
	return c:IsSetCard(0x2) and c:IsType(TYPE_TUNER)

```

2023-12-31 09:05 UTC, closed without merging