Add cards from LEDE-JP
Fluorohydride/ygopro-pre-script pull request #1236
Opened 2023-11-11 18:44 UTC by StupidStudiosN

2023-11-18 04:21 UTC, pokeboyexn commented
Hi, may I know what is your contact? Not sure if you are in discord or on QQ. Some of the scripts have bugs and require some testing, which we have already tested. Let's sync and prevent duplicated work/efforts.

2023-11-18 04:29 UTC, StupidStudiosN commented
> Hi, may I know what is your contact? Not sure if you are in discord or on QQ. Some of the scripts have bugs and require some testing, which we have already tested. Let's sync and prevent duplicated work/efforts.

Sure, it's StupidStudiosN on Discord as well.  Reach out to me through DMs, and I'd be happy to help.

2023-11-24 06:02 UTC, Crescent0v0 commented on scripts/LEDE-JP/c101204005.lua
> +	return c:IsCode(id) and c:IsCanBeSpecialSummoned(e,0,tp,false,false) and (c:IsLocation(LOCATION_HAND+LOCATION_GRAVE) or c:IsFaceup())
```suggestion
	return c:IsCode(id) and c:IsCanBeSpecialSummoned(e,0,tp,false,false) and (c:IsLocation(LOCATION_HAND+LOCATION_DECK) or c:IsFaceup())

```

2023-11-29 03:20 UTC, fallenstardust commented on scripts/LEDE-JP/c101204004.lua
> +	return c:IsCode(101204051) or (aux.IsCodeListed(c,101204051) and c:IsType(TYPE_SPELL+TYPE_TRAP)) and c:IsAbleToHand()
return (c:IsCode(101204051) or aux.IsCodeListed(c,101204051) and c:IsType(TYPE_SPELL+TYPE_TRAP)) and c:IsAbleToHand()

2023-11-29 03:24 UTC, fallenstardust commented on scripts/LEDE-JP/c101204004.lua
> +	return c:IsCode(101204051) or (aux.IsCodeListed(c,101204051) and c:IsType(TYPE_SPELL+TYPE_TRAP)) and c:IsAbleToHand()
```suggestion
	return (c:IsCode(101204051) or aux.IsCodeListed(c,101204051) and c:IsType(TYPE_SPELL+TYPE_TRAP)) and c:IsAbleToHand()

```

2023-11-29 03:24 UTC, fallenstardust commented on scripts/LEDE-JP/c101204004.lua
> +	return c:IsCode(101204051) or (aux.IsCodeListed(c,101204051) and c:IsType(TYPE_SPELL+TYPE_TRAP)) and c:IsAbleToHand()
```suggestion
	return (c:IsCode(101204051) or aux.IsCodeListed(c,101204051) and c:IsType(TYPE_SPELL+TYPE_TRAP)) and c:IsAbleToHand()

```

2023-12-10 12:43 UTC, Wind2009-Louse requested changes

2023-12-27 08:38 UTC, Wind2009-Louse commented on scripts/TW01-JP/c100211122.lua
> +	return c:IsFaceup() and c:IsControler(tp) and c:IsLocation(LOCATION_MZONE)
Should be able to replace the destruction in Spell & Trap Zones

2023-12-27 14:46 UTC, Wind2009-Louse commented on scripts/TW01-JP/c100211122.lua
> +end
```suggestion
function s.repfilter(c,tp)
	return c:IsFaceup() and c:IsControler(tp) and c:IsOnField()
		and c:IsSetCard(0xb5) and c:IsReason(REASON_BATTLE+REASON_EFFECT) and not c:IsReason(REASON_REPLACE)
end
```

2024-01-20 07:02 UTC, merged