add AC02 cards
Fluorohydride/ygopro-pre-script pull request #962
Opened 2022-06-01 03:10 UTC by Trishula9

2022-06-01 19:49 UTC, Lyris12 requested changes
While you have no available Monster Zones, no effect should be able to copy the effect of "Dimension Dice" when the latter name activates.

2022-06-01 19:49 UTC, Lyris12 commented on scripts/AC02-JP/c100290006.lua
> +	if chk==0 then return Duel.IsExistingMatchingCard(c100290006.spfilter,tp,LOCATION_HAND+LOCATION_DECK,0,1,nil,e,tp) end
```suggestion
	if chk==0 then
		if e:GetLabel()~=1 then return false end
		e:SetLabel(0)
		return Duel.IsExistingMatchingCard(c100290006.spfilter,tp,LOCATION_HAND+LOCATION_DECK,0,1,nil,e,tp)
	end
```

2022-06-01 19:49 UTC, Lyris12 commented on scripts/AC02-JP/c100290006.lua
> +	if chk==0 then return Duel.CheckReleaseGroup(tp,c100290006.rfilter,1,nil,tp) end
```suggestion
	e:SetLabel(1)
	if chk==0 then return Duel.CheckReleaseGroup(tp,c100290006.rfilter,1,nil,tp) end
```

2022-06-01 19:49 UTC, Lyris12 commented on scripts/AC02-JP/c100290006.lua
> +	e1:SetCondition(c100290006.condition)
```suggestion
	e1:SetLabel(0)
	e1:SetCondition(c100290006.condition)
```

2022-06-04 04:27 UTC, Lyris12 requested changes
The effect code, `EFFECT_SELF_TOGRAVE`, requires `GLOBALFLAG_SELF_TOGRAVE` to be enabled in that duel to work.

2022-06-04 04:27 UTC, Lyris12 commented on scripts/AC02-JP/c100290010.lua
> +function c100290010.initial_effect(c)
```suggestion
function c100290010.initial_effect(c)
	Duel.EnableGlobalFlag(GLOBALFLAG_SELF_TOGRAVE)
```

2022-06-04 04:27 UTC, Lyris12 commented on scripts/AC02-JP/c100290011.lua
> +function c100290011.initial_effect(c)
```suggestion
function c100290011.initial_effect(c)
	Duel.EnableGlobalFlag(GLOBALFLAG_SELF_TOGRAVE)
```

2022-06-04 04:27 UTC, Lyris12 commented on scripts/AC02-JP/c100290012.lua
> +function c100290012.initial_effect(c)
```suggestion
function c100290012.initial_effect(c)
	Duel.EnableGlobalFlag(GLOBALFLAG_SELF_TOGRAVE)
```

2022-06-04 04:27 UTC, Lyris12 commented on scripts/AC02-JP/c100290013.lua
> +function c100290013.initial_effect(c)
```suggestion
function c100290013.initial_effect(c)
	Duel.EnableGlobalFlag(GLOBALFLAG_SELF_TOGRAVE)
```

2022-06-04 04:27 UTC, Lyris12 commented on scripts/AC02-JP/c100290014.lua
> +function c100290014.initial_effect(c)
```suggestion
function c100290014.initial_effect(c)
	Duel.EnableGlobalFlag(GLOBALFLAG_SELF_TOGRAVE)
```

2022-06-04 04:27 UTC, Lyris12 commented on scripts/AC02-JP/c100290015.lua
> +function c100290015.initial_effect(c)
```suggestion
function c100290015.initial_effect(c)
	Duel.EnableGlobalFlag(GLOBALFLAG_SELF_TOGRAVE)
```

2022-06-04 04:27 UTC, Lyris12 commented on scripts/AC02-JP/c100290016.lua
> +function c100290016.initial_effect(c)
```suggestion
function c100290016.initial_effect(c)
	Duel.EnableGlobalFlag(GLOBALFLAG_SELF_TOGRAVE)
```

2022-06-04 06:26 UTC, Trishula9 commented
> The effect code, `EFFECT_SELF_TOGRAVE`, requires `GLOBALFLAG_SELF_TOGRAVE` to be enabled in that duel to work.

Thank you for bug resolution

2022-06-07 21:34 UTC, Lyris12 commented on scripts/AC02-JP/c100290014.lua
> +	e4:SetDescription(aux.Stringid(100290014,0))
```suggestion
	e3:SetDescription(aux.Stringid(100290014,0))
```

2022-06-09 00:19 UTC, chronogenexx commented
Doodle Beast and Doodlebook's japanese name is mistaken.

and, it would be better to use this:
```
#!setname 0x286 Doodle	らくがき
!setname 0x1286 Doodle Beast	らくがきじゅう
!setname 0x2286 Doodlebook	らくがきちょう
```

2022-06-09 06:18 UTC, merged